name: authentication
description: "Authentication feature for the Hives project."
version: 0.0.1
environment:
  sdk: ^3.10.3
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  shared: 0.0.1
  fpdart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
